# Generated by Django 2.0 on 2019-06-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0010_delete_vendorpaycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost')], default='Percentage', max_length=128)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_affected_items', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_all_products', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(to='catalogue.ProductClass')),
                ('excluded_products', models.ManyToManyField(related_name='excluded_products', to='catalogue.Product')),
                ('included_brands', models.ManyToManyField(to='catalogue.Brand')),
                ('included_categories', models.ManyToManyField(to='catalogue.Category')),
                ('included_products', models.ManyToManyField(related_name='included_products', to='catalogue.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='This will be shown in the checkout and basket once the voucher is entered', max_length=128, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Code')),
                ('usage', models.CharField(choices=[('Single use', 'Can be used once by one customer'), ('Multi-use', 'Can be used multiple times by multiple customers'), ('Once per customer', 'Can only be used once per customer')], default='Multi-use', max_length=128)),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('num_basket_additons', models.PositiveIntegerField(default=0)),
                ('num_orders', models.PositiveIntegerField(default=0)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description for the costumers')),
                ('offer_type', models.CharField(choices=[('Site', 'Site offer - available to all users and products'), ('Category', 'Category offer - only available for certain categories '), ('Brand', 'Brand offer - available to certain brands'), ('Products', 'Products offer - Manual add Products')], default='Site', max_length=128)),
                ('exclusive', models.BooleanField(default=True)),
                ('status', models.CharField(default='Open', max_length=64, verbose_name='Status')),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('max_global_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('max_user_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('max_basket_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('num_applications', models.PositiveIntegerField(default=0)),
                ('num_orders', models.PositiveIntegerField(default=0)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.Voucher')),
            ],
        ),
        migrations.AddField(
            model_name='productrange',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.Voucher'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.Voucher'),
        ),
    ]
