# Generated by Django 2.0 on 2019-06-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20190630_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherrules',
            name='name',
        ),
    ]
