# Generated by Django 2.0.7 on 2019-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20190630_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='max_affected_items',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost')], default='Percentage', max_length=128, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Χρήση εώς'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='num_basket_additons',
            field=models.PositiveIntegerField(default=0, verbose_name='Συνολικές Προσθήκες στο καλάθι'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='num_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Συνολικές Προσθήκες στις Παραγγελίες'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Χρήση από'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage',
            field=models.CharField(choices=[('Single use', 'Χρήση μόνο μια φορά'), ('Multi-use', 'Πολλαπλή Χρήση από όλους'), ('Once per customer', 'Χρήση μια φορά ανά Πελάτη')], default='Multi-use', max_length=128, verbose_name='Είδος Χρήσης'),
        ),
    ]
