# Generated by Django 2.0.7 on 2019-07-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_auto_20190702_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherrules',
            name='status',
        ),
    ]
