# Generated by Django 2.0.7 on 2019-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20190707_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
