# Generated by Django 2.0.7 on 2019-07-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_auto_20190707_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrules',
            name='benefit_type',
            field=models.CharField(choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Reduce the cost of order by the value'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost')], default='Percentage', max_length=128, verbose_name='Discount Type'),
        ),
    ]
