# Generated by Django 2.0.7 on 2019-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190514_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperson',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
