# Generated by Django 2.0.7 on 2019-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190514_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperson',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
