# Generated by Django 2.0 on 2019-05-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190514_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='warehouse.GenericExpenseCategory', verbose_name='Κατηγορία Εξόδων'),
        ),
        migrations.AlterField(
            model_name='genericexpense',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_invoices', to='warehouse.GenericPerson', verbose_name="Εταιρία/'Ατομο"),
        ),
    ]
