# Generated by Django 2.0.7 on 2019-05-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190509_1540'),
        ('warehouse', '0007_auto_20190516_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttributeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('attribute_related', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Attribute')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.InvoiceOrderItem')),
            ],
        ),
    ]
