# Generated by Django 2.0.7 on 2019-05-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_invoiceattributeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_type',
            field=models.CharField(choices=[('1', 'Τιμολόγιο - Δελτίο Αποστολής'), ('2', 'Τιμολόγιο'), ('3', 'Δελτίο Απόστολης'), ('4', 'Εισαγωγή Αποθήκης'), ('5', 'Εξαγωγή Αποθήκης'), ('6', 'Προπαραγγελία')], default=1, max_length=1, verbose_name='Είδος'),
        ),
        migrations.AlterField(
            model_name='invoiceattributeitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_attributes', to='warehouse.InvoiceOrderItem'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceorderitem',
            unique_together=set(),
        ),
    ]
