# Generated by Django 2.0.7 on 2019-06-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_invoiceorderitem_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceattributeitem',
            name='attribute_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attributes', to='catalogue.Attribute'),
        ),
    ]
