# Generated by Django 2.0.7 on 2019-06-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20190613_0818'),
        ('catalogue', '0009_auto_20190622_1547'),
        ('warehouse', '0012_auto_20190618_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('date_expired', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paycheck',
        ),
        migrations.AddField(
            model_name='vendorpaycheck',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='warehouse.Invoice'),
        ),
        migrations.AddField(
            model_name='vendorpaycheck',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='vendorpaycheck',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_paychecks', to='catalogue.Vendor'),
        ),
    ]
