# Generated by Django 2.0 on 2019-06-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20190622_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='date_expired',
            field=models.DateField(verbose_name='Ημερμηνία λήξης'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='warehouse.Invoice', verbose_name='Τιμολόγιο'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Πληρωμένη Αξία'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_paychecks', to='catalogue.Vendor', verbose_name='Προμηθευτής'),
        ),
    ]
