# Generated by Django 2.0.7 on 2019-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0005_auto_20190607_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('title', models.CharField(max_length=200, unique=True)),
                ('choices', models.CharField(choices=[{'Ποσοστό', 'a'}, ('b', 'Ποσό'), ('c', 'Ακριβές Ποσό')], max_length=1)),
                ('discount_type', models.CharField(choices=[('a', 'Έκπτωση Brand'), ('b', 'Έκπτωση Κατηγοριών'), ('c', 'Έκπτωση Προϊόντων')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_related', models.ManyToManyField(to='catalogue.Product')),
            ],
        ),
    ]
