# Generated by Django 2.0.7 on 2019-06-08 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 8, 7, 41, 5, 734240)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='choices',
            field=models.CharField(choices=[{'Ποσοστό', 'a'}, ('b', 'Ποσό'), ('c', 'Ακριβές Ποσό')], max_length=1, verbose_name='Τρόπος Έκπτωσεις'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='date_end',
            field=models.DateField(blank=True, help_text='Αν μείνει κενό διαρκεί για πάντα', verbose_name='Ημερομηνία Μέχρι..'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='date_start',
            field=models.DateField(blank=True, verbose_name='Ημερομηνία Από..'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('a', 'Έκπτωση Brand'), ('b', 'Έκπτωση Κατηγοριών'), ('c', 'Έκπτωση Προϊόντων')], max_length=1, verbose_name='Έιδος Έκπτωσης'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Αξία'),
        ),
    ]
