# Generated by Django 2.0.7 on 2019-06-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190608_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdiscount',
            old_name='choices',
            new_name='my_choices',
        ),
    ]
