# Generated by Django 2.0.7 on 2019-06-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190608_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='date_end',
            field=models.DateField(blank=True, help_text='Αν μείνει κενό διαρκεί για πάντα', null=True, verbose_name='Ημερομηνία Μέχρι..'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Από..'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='my_choices',
            field=models.CharField(choices=[('a', 'Ποσοστό'), ('b', 'Ποσό'), ('c', 'Ακριβές Ποσό')], max_length=1, verbose_name='Τρόπος Έκπτωσεις'),
        ),
    ]
