# Generated by Django 2.0.7 on 2019-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190608_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='my_choices',
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('a', 'Ποσοστό'), ('b', 'Ποσό'), ('c', 'Ακριβές Ποσό')], max_length=1, verbose_name='Έιδος Έκπτωσης'),
        ),
    ]
