# Generated by Django 2.0 on 2019-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Κινητό'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Επίθετο'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση Αποστολής'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Τκ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Off the record Manual Balance', max_digits=20, verbose_name='Επιπλέον Αξία'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vat_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Εφορία'),
        ),
    ]
