# Generated by Django 2.0.7 on 2019-05-09 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_auto_20190423_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 9, 12, 40, 8, 884010, tzinfo=utc), verbose_name='Date'),
        ),
    ]
