# Generated by Django 2.0 on 2019-05-11 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20190509_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 5, 5, 28, 715272, tzinfo=utc), verbose_name='Date'),
        ),
    ]
