# Generated by Django 2.0.7 on 2019-05-14 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20190511_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 4, 45, 36, 97484, tzinfo=utc), verbose_name='Date'),
        ),
    ]
