# Generated by Django 2.0.7 on 2019-05-14 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0010_auto_20190514_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 5, 46, 55, 527134, tzinfo=utc), verbose_name='Date'),
        ),
    ]
