# Generated by Django 2.0 on 2019-05-16 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20190514_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 11, 18, 42, 879464, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Πληρωμένο'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Πώληση Eshop'), ('b', 'Παραστατικό Επιστροφής'), ('c', 'Ακυρωμένη Παραγγελία'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1, verbose_name='Είδος'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Πληρωτέο Ποσό'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='order',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='Εκτυπωμένο'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε επεξεργασία'), ('3', 'Έτοιμη προς αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='1', max_length=1, verbose_name='ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικο Κόστος'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Αρχική Αξία'),
        ),
    ]
