# Generated by Django 2.0.7 on 2019-05-19 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0013_auto_20190516_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 17, 56, 51, 294036, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
