# Generated by Django 2.0.7 on 2019-05-20 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0014_auto_20190519_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 5, 20, 8, 50, 54, 580812, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
