# Generated by Django 2.0.7 on 2019-06-08 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0018_auto_20190607_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 8), verbose_name='Ημερομηνία'),
        ),
    ]
