# Generated by Django 2.0.7 on 2019-06-14 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0020_auto_20190613_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 14), verbose_name='Ημερομηνία'),
        ),
    ]
