# Generated by Django 2.0.7 on 2019-06-18 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0021_auto_20190614_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 18), verbose_name='Ημερομηνία'),
        ),
    ]
