# Generated by Django 2.0.7 on 2019-06-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0022_auto_20190618_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 22), verbose_name='Ημερομηνία'),
        ),
    ]
