# Generated by Django 2.0 on 2019-06-29 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0023_auto_20190622_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 29), verbose_name='Ημερομηνία'),
        ),
    ]
