# Generated by Django 2.0 on 2019-06-30 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0024_auto_20190629_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 6, 30), verbose_name='Ημερομηνία'),
        ),
    ]
