# Generated by Django 2.0.7 on 2019-07-02 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0025_auto_20190630_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 2), verbose_name='Ημερομηνία'),
        ),
    ]
