# Generated by Django 2.0 on 2019-07-03 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0026_auto_20190702_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 3), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1, verbose_name='ΦΠΑ'),
        ),
    ]
