# Generated by Django 2.0.7 on 2019-07-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20190703_1500'),
        ('point_of_sale', '0028_auto_20190703_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shipping_code', models.CharField(blank=True, max_length=240)),
                ('order_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Shipping')),
            ],
        ),
    ]
