# Generated by Django 2.0.7 on 2019-07-04 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0029_sendreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='order_related',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order_related',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 4), verbose_name='Ημερομηνία'),
        ),
    ]
