# Generated by Django 2.0.7 on 2019-07-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0030_auto_20190704_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='order_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order'),
        ),
    ]
