# Generated by Django 2.0.7 on 2019-07-05 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0031_auto_20190704_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 5), verbose_name='Ημερομηνία'),
        ),
    ]
