# Generated by Django 2.0 on 2019-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_remove_voucherrules_status'),
        ('point_of_sale', '0032_auto_20190705_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vouchers',
            field=models.ManyToManyField(to='voucher.Voucher'),
        ),
    ]
