# Generated by Django 2.0 on 2019-07-07 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0033_order_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 7), verbose_name='Ημερομηνία'),
        ),
    ]
