# Generated by Django 2.0.7 on 2019-07-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0035_auto_20190708_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_expired', 'status', '-id'], 'verbose_name': 'Order', 'verbose_name_plural': '1. Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 7, 10), verbose_name='Ημερομηνία'),
        ),
    ]
