# Generated by Django 2.0.7 on 2019-05-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190509_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Vendor', verbose_name='Προμηθευτής'),
        ),
    ]
