# Generated by Django 2.0.7 on 2019-06-07 14:50

import catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190520_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Σχόλια'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='610*410', null=True, upload_to=catalogue.validators.category_site_directory_path, verbose_name='Εικόνα'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Τίτλος'),
        ),
    ]
