# Generated by Django 2.0.7 on 2019-06-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190607_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='attributeclass',
            name='have_transcations',
            field=models.BooleanField(default=True, verbose_name='Υποστηρίζει Συναλλαγές'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_add',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='we use this for manual add.', max_digits=10, verbose_name='Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_measure',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=5, verbose_name='Ποσότητα Ανά Τεμάχιο'),
        ),
    ]
