# Generated by Django 2.0.7 on 2019-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190614_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_measure',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Ποσότητα Ανά Τεμάχιο'),
        ),
    ]
