# Generated by Django 2.0.7 on 2019-06-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20190618_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpaycheck',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='vendorpaycheck',
            name='vendor',
        ),
    ]
