# Generated by Django 2.0.7 on 2019-06-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190622_1547'),
        ('warehouse', '0013_auto_20190622_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorPaycheck',
        ),
    ]
