# Generated by Django 2.0.7 on 2019-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190710_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='characteristicsvalue',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
