# Generated by Django 2.0 on 2019-07-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20190702_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city_zip', models.CharField(max_length=5)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_fax', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Σχόλiα'),
        ),
    ]
