# Generated by Django 2.0.7 on 2019-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20190703_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_city_zip',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_fax',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
