# Generated by Django 2.0.7 on 2019-06-07 14:50

import cart.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Έκπτωση'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod', verbose_name='Αντικαταβολή'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Shipping', verbose_name='Τρόπος Μεταφοράς'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[cart.validators.validate_positive_decimal], verbose_name='Αξία Προϊόντων'),
        ),
    ]
