# Generated by Django 2.0.7 on 2019-07-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_remove_voucherrules_status'),
        ('cart', '0002_auto_20190607_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vouchers',
            field=models.ManyToManyField(to='voucher.Voucher'),
        ),
    ]
