# Generated by Django 2.0.7 on 2019-07-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Έκπτωση από Κουπόνια'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cart.Cart'),
        ),
    ]
